### ISSUE TITLE
values have double.NaN.Chart data labels lost and offset when exported to PDF

### ISSUE THREAD

**Issue by weibinlong** [aspose-words/Aspose.Words-for-.NET#274] opened 2020-01-06 08:20 UTC
`public static void DefaultOptionsForDataLabels(string dataDir)
        {
            // ExStart:DefaultOptionsForDataLabels
            Document doc = new Document();
            DocumentBuilder builder = new DocumentBuilder(doc);

            Shape shape = builder.InsertChart(ChartType.Line, 432, 252);
            Chart chart = shape.Chart;
            chart.Series.Clear();

            ChartSeries series = chart.Series.Add("Series 1",
                new string[] { "Category0", "Category1", "Category2", "Category3", "Category4", "Category5" },
                new double[] { double.NaN, 2.1, 3.2, double.NaN, 0.8, 3.8 });

            ChartDataLabelCollection labels = series.DataLabels;
            //labels.ShowPercentage = true;
            labels.ShowValue = true;
            //labels.ShowLeaderLines = false;
            //labels.Separator = " - ";

            doc.Save(dataDir + "Demo.docx"); 
            doc.Save(dataDir + "Demo.pdf", SaveFormat.Pdf);
            // ExEnd:DefaultOptionsForDataLabels
            Console.WriteLine("\nDefault options for data labels of chart series created successfully.\nFile saved at " + dataDir);
        }`
Hi, guys, values have double.NaN.Chart data labels lost and offset when exported to PDF.Please see the attachment below
[Demo.docx](https://github.com/aspose-words/Aspose.Words-for-.NET/files/4025228/Demo.docx)
[Demo.pdf](https://github.com/aspose-words/Aspose.Words-for-.NET/files/4025232/Demo.pdf)

![image](https://user-images.githubusercontent.com/16573133/71805076-37f62400-30a0-11ea-9324-e2e7e30c7b8d.png)
//..\Aspose.Words-for-.NET\Examples\CSharp\Programming-Documents\Charts\WorkWithChartDataLabels.cs

**Comment by AlexNosk** [comment] 2020-01-06 09:09
@weibinlong Thank you for reporting this problem to us. I managed to reproduce it on my side. The problem is logged in our bug tracking system as issue WORDSNET-19779. We will let you know once it is resolved.

**Comment by AlexNosk** [comment] 2020-02-12 07:42
@weibinlong The issue you have found is already resolved in the latest version of [Aspose.Words](https://www.nuget.org/packages/Aspose.Words).

**Closed by AlexNosk** 2020-02-12 07:42 UTC

**Comment by weibinlong** [comment] 2020-02-28 01:50
> @weibinlong The issue you have found is already resolved in the latest version of [Aspose.Words](https://www.nuget.org/packages/Aspose.Words).

Ok. Thanks very much.
